### ISSUE TITLE
README文件完善需求

### ISSUE THREAD

**Issue by GSJ-SD** [Snoopy1866/RTFTools-For-SAS#1]
建议完善README文件，包含宏程序使用顺序及说明、每次更新迭代说明等~

**Comment by Snoopy1866** [comment]
收到，在计划中。

**Comment by Snoopy1866** [comment]
已更新说明文件

**Comment by Snoopy1866** [comment]
更新迭代详见 [Releases](https://github.com/Snoopy1866/RTFTools-For-SAS/releases) 页面
